### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by donbowen**
Hi Yang, working on your rec letter now. Let's polish your website.

1. You should accept these changes in this "pull request". (Minor things: Some tweaking of language. I also fixed a broken link.)
2. If you want, take a look at your [NLP page](https://yal521.github.io/YangLiu/analysis_report-2) and your [regression page](https://yal521.github.io/YangLiu/regression). It's pretty easy to improve those by changing the corresponding md files [here](https://github.com/yal521/YangLiu/blob/master/analysis_report-2.md) and [here](https://github.com/yal521/YangLiu/blob/master/Regression_practice.md)

### CODE REVIEW

**Comment by donbowen** [comment]
@yal521

**Comment by donbowen** [comment]
One more easy suggestion: Your website has the same picture twice. You can upload a second picture to the image folder [here](https://github.com/yal521/YangLiu/tree/master/images) and then [update the home page](https://github.com/yal521/YangLiu/edit/master/index.md) by changing the filename on line 10.

**Comment by yal521** [comment]
@donbowen thank you professor Bowen for your suggestion. I am now working on it. 
(1) edit md file is for making it show beautifully without weird signals
(2) about the pictures: what you mean is that I can show two different picture about myself on website
:)

**Comment by donbowen** [comment]
I added one more tiny change. If you accept this pull request, I think your "Resume" link will just open the pdf itself directly now. 

@yal521

**Pull request merged**
